### ISSUE TITLE
OpenSource Consent?

### ISSUE THREAD

**Issue by aliceseaborn** [lorenzo85/scenarios-ica#4]
Greetings,

I have been studying for the ICA using your scenarios in KillerCoda and they're fantastic. I noticed in the README that you allow people to fork this repository but I also noticed that there is no license included with this repository. Is this work FOSS and, if so, would you consider adding a license to reflect your preferred consent model?

Thanks!
~alice

**Comment by lorenzo85** [comment]
Hi @aliceseaborn, thank you! 

Added license file here: https://github.com/lorenzo85/scenarios-ica/blob/master/LICENSE

Thank you;
Lorenzo
